trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Ansible_Test
    displayName: "Run Ansible Tests on Windows Host"
    jobs:
      - job: RunAnsible
        displayName: "Execute Ansible Playbooks"
        variables:
          WIN_USERNAME: $(win_username)   
          WIN_PASSWORD: $(win_password) 

        steps:

          # Install dependencies
          - task: Bash@3
            displayName: "Install Ansible & dependencies"
            inputs:
              targetType: inline
              script: |
                sudo apt-get update -y
                sudo apt-get install -y python3-pip
                pip3 install ansible pywinrm
                ansible-galaxy collection install -r requirements.yml

          # Run Connectivity Test
          - task: Bash@3
            displayName: "Run Ansible Connectivity Check"
            env:
              WIN_USERNAME: $(win_username)
              WIN_PASSWORD: $(win_password)
            inputs:
              targetType: inline
              script: |
                ansible-playbook playbooks/connectivity.yml

          # Install Notepad++
          - task: Bash@3
            displayName: "Run Notepad++ Install"
            env:
              WIN_USERNAME: $(win_username)
              WIN_PASSWORD: $(win_password)
            inputs:
              targetType: inline
              script: |
                ansible-playbook playbooks/install_notepadpp.yml
