trigger:
  - main  

pool:
  vmImage: 

stages:
  - stage: Ansible_Test
    displayName: "Run Ansible Tests on Windows Host"
    jobs:
      - job: RunAnsible
        displayName: "Execute Ansible Playbooks"
        steps:

          # Step 1: Install dependencies
          - task: Bash@3
            displayName: "Install Ansible & dependencies"
            inputs:
              targetType: inline
              script: |
                sudo apt-get update -y
                sudo apt-get install -y python3-pip
                pip3 install ansible pywinrm
                ansible-galaxy collection install -r requirements.yml

          # Step 2: Run Connectivity Test
          - task: Bash@3
            displayName: "Run Ansible Connectivity Check"
            inputs:
              targetType: inline
              script: |
                ansible-playbook playbooks/connectivity.yml -i inventories/windows.yml

          # Step 3: Install Notepad++
          - task: Bash@3
            displayName: "Run Notepad++ Install"
            inputs:
              targetType: inline
              script: |
                ansible-playbook playbooks/install_notepadpp.yml -i inventories/windows.yml
